# nixpacks.toml
# Static site build configuration for Railway
# React app with PlayFab integration (no server needed)
# Author: Cascade AI

[phases.setup]
# Ensure Node.js 18 for Vite build process
nixPkgs = ["nodejs_18"]

[phases.install]
# Use npm ci for clean install
cmds = ["npm ci"]

[phases.build]
# Build React client only - PlayFab handles all backend functionality
# Vite builds client to dist/ for static deployment
cmds = ["npm run build:client"]
