# nixpacks.toml
# Nixpacks build configuration for Railway
# Full-stack React + Node.js with PlayFab integration
# Author: Cascade AI

[phases.setup]
# Ensure Node.js 18 and any other system dependencies
nixPkgs = ["nodejs_18"]

[phases.install]
# Use npm ci for clean install
cmds = ["npm ci"]

[phases.build]
# Build both the React client (Vite) and Node.js server (esbuild)
# Vite builds client to dist/public, esbuild bundles server to dist/index.js
cmds = ["npm run build"]

[start]
# Start the bundled Node.js server (serves API + static client files)
cmd = "node dist/index.js"
