# nixpacks.toml
# Static site build configuration for Railway  
# React app with PlayFab-only backend (no server needed)
# Author: Cascade AI

[phases.setup]
# Ensure Node.js 18 for Vite build process
nixPkgs = ["nodejs_18"]

[phases.install]
# Use npm ci for clean install
cmds = ["npm ci"]

[phases.build]
# Build React client only - PlayFab handles all backend functionality
# Vite builds static site to dist/
cmds = ["npm run build:client"]
