# railway.toml
# Static site deployment configuration for Railway
# React app with PlayFab integration (no server needed)
# Author: Cascade AI

[build]
# Build React client only - PlayFab handles all backend functionality
command = "npm ci && npm run build:client"

[deploy]
# Static site deployment - no server process needed
staticPublishPath = "dist"
