# railway.toml  
# Static site deployment configuration for Railway
# React app with PlayFab-only backend (no server needed)
# Author: Cascade AI

[build]
# Build React client only - PlayFab handles all backend functionality
command = "npm ci && npm run build:client"

[deploy]
# Static site deployment - PlayFab handles all data/API needs
staticPublishPath = "dist"
